#!/usr/bin/env bash
# Install GPU Server Dashboard as a systemd user service (auto-starts on boot).
#
# Usage:
#   ./install_service.sh                           # use defaults
#   ./install_service.sh --port 9090               # custom port
#   ./install_service.sh --config servers_rp.yaml --interval 5
#
# What this does:
#   1. Creates a systemd user unit at ~/.config/systemd/user/gpu-dashboard.service
#   2. Enables lingering so the service starts at boot (no login required)
#   3. Enables and starts the service

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
DASHBOARD_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"

# ---- defaults ---------------------------------------------------------------
PORT=8080
CONFIG="servers.yaml"
INTERVAL=10
SSH_TIMEOUT=5
VERBOSE=""

# ---- parse args -------------------------------------------------------------
while [[ $# -gt 0 ]]; do
    case "$1" in
        --port)       PORT="$2";       shift 2 ;;
        --config)     CONFIG="$2";     shift 2 ;;
        --interval)   INTERVAL="$2";   shift 2 ;;
        --ssh-timeout) SSH_TIMEOUT="$2"; shift 2 ;;
        --verbose|-v) VERBOSE="--verbose"; shift ;;
        *)
            echo "Unknown option: $1"
            echo "Usage: $0 [--port PORT] [--config CONFIG] [--interval N] [--ssh-timeout N] [--verbose]"
            exit 1
            ;;
    esac
done

# ---- python detection -------------------------------------------------------
PYTHON="$(which python3 || which python)"
echo "Using python: $PYTHON"

# ---- capture desktop environment -------------------------------------------
ENV_FILE="$HOME/.config/gpu-dashboard.env"

cat > "$ENV_FILE" << EOF
# Auto-generated by install_service.sh — preserves desktop session env
DISPLAY=${DISPLAY:-:0}
WAYLAND_DISPLAY=${WAYLAND_DISPLAY:-}
DBUS_SESSION_BUS_ADDRESS=${DBUS_SESSION_BUS_ADDRESS:-unix:path=/run/user/${UID}/bus}
XAUTHORITY=${XAUTHORITY:-$HOME/.Xauthority}
EOF

echo "Desktop environment saved to: $ENV_FILE"
git -C "$DASHBOARD_DIR" log --oneline -1 2>/dev/null && echo ""

# ---- generate service unit --------------------------------------------------
SERVICE_NAME="gpu-dashboard"
UNIT_DIR="${XDG_CONFIG_HOME:-$HOME/.config}/systemd/user"
UNIT_FILE="$UNIT_DIR/$SERVICE_NAME.service"

mkdir -p "$UNIT_DIR"

cat > "$UNIT_FILE" << EOF
# GPU Server Dashboard — auto-generated by install_service.sh
# Location: $UNIT_FILE

[Unit]
Description=GPU Server Resource Dashboard
After=network-online.target graphical-session.target
Wants=network-online.target

[Service]
Type=simple
EnvironmentFile=$ENV_FILE
WorkingDirectory=$DASHBOARD_DIR
ExecStart=$PYTHON $DASHBOARD_DIR/run_dashboard.py web \\
    --config $DASHBOARD_DIR/$CONFIG \\
    --port $PORT \\
    --interval $INTERVAL \\
    --ssh-timeout $SSH_TIMEOUT \\
    --host 0.0.0.0 \\
    $VERBOSE
ExecStop=/bin/kill -TERM \$MAINPID
Restart=always
RestartSec=5

# Relax sandboxing so VSCode/terminal can connect to the desktop
NoNewPrivileges=no
PrivateTmp=no

[Install]
WantedBy=default.target
EOF

echo ""
echo "Unit file written to: $UNIT_FILE"
echo "---"
cat "$UNIT_FILE"
echo "---"

# ---- enable lingering (allows user services to start at boot) ----------------
loginctl enable-linger "$USER" 2>/dev/null || true
echo "Lingering enabled for user '$USER'"

# ---- reload, enable, start ---------------------------------------------------
systemctl --user daemon-reload
systemctl --user enable "$SERVICE_NAME"
systemctl --user restart "$SERVICE_NAME"

echo ""
echo "Service '$SERVICE_NAME' installed and started."
echo ""
echo "Useful commands:"
echo "  systemctl --user status $SERVICE_NAME"
echo "  journalctl --user -u $SERVICE_NAME -f"
echo "  ./scripts/uninstall_service.sh"
